"""Check and split a ``speculators regenerate-responses`` corpus for online training.

The DSpark corpus (open-perfectblend regenerated by Apertus 8B) was written by
speculators' ``regenerate-responses``: one JSON row per regenerated assistant
turn, ``{"id": "<conv>_gen<k>", "primary_id": "<conv>", "input_ids": prompt +
completion, "loss_mask": 0 on the prompt / 1 on the completion, "text",
"metadata": {"finish_reason", "usage", "sampling_params", ...}}``. Each turn is
generated after the model's own earlier answers, so a row's prompt holds the
regenerated history. ``online_features`` trains on these rows as they are
(pre-tokenized ``input_ids`` + ``loss_mask``); this module only checks that a
file has that shape and splits it by conversation.

    check: counts, token and length statistics, finish reasons, problems
    split: rows listed in --heldout-ids -> heldout.jsonl, the rest -> train.jsonl.
           Ids are matched against the row id (``opb-<conv>_gen<k>``, as the DSpark
           run's val_ids.txt) or, with --by conversation, the conversation id.
    prompts: the first rows' prompts (the tokens before the completion, exactly as
           the server rendered them, thinking mode included) as ``prompt_ids`` rows
           for ``verify_offline``, which would otherwise render them without thinking.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


def row_problems(row: dict[str, Any]) -> list[str]:
    """Why a row cannot be trained on as-is (empty list: fine)."""
    ids, mask = row.get("input_ids"), row.get("loss_mask")
    if not isinstance(ids, list) or not isinstance(mask, list):
        return ["missing input_ids/loss_mask"]
    problems = []
    if len(ids) != len(mask):
        problems.append("length mismatch")
    if not any(mask):
        problems.append("no loss tokens")
    # regenerate-responses masks one contiguous completion at the end.
    first = next((i for i, m in enumerate(mask) if m), len(mask))
    if any(not m for m in mask[first:]):
        problems.append("loss mask not a single trailing span")
    if not all(isinstance(t, int) and t >= 0 for t in ids):
        problems.append("non-integer token id")
    return problems


def conversation_id(row: dict[str, Any]) -> str:
    return str(row.get("primary_id") or str(row.get("id", "")).rsplit("_gen", 1)[0])


def percentiles(values: list[int]) -> dict[str, float] | None:
    if not values:
        return None
    ordered = sorted(values)
    at = lambda q: ordered[min(len(ordered) - 1, int(q * len(ordered)))]  # noqa: E731
    return {"mean": sum(ordered) / len(ordered), "p50": at(0.5), "p90": at(0.9),
            "p99": at(0.99), "max": ordered[-1]}  # fmt: skip


def check(paths: list[Path], max_seq_length: int) -> dict[str, Any]:
    lengths, completions = [], []
    problems: Counter[str] = Counter()
    finish: Counter[str] = Counter()
    conversations: set[str] = set()
    rows = bad = 0
    for path in paths:
        with path.open() as handle:
            for line in handle:
                if not line.strip():
                    continue
                row = json.loads(line)
                rows += 1
                found = row_problems(row)
                if found:
                    bad += 1
                    problems.update(found)
                    continue
                conversations.add(conversation_id(row))
                lengths.append(len(row["input_ids"]))
                completions.append(sum(row["loss_mask"]))
                finish[str((row.get("metadata") or {}).get("finish_reason"))] += 1
    total = sum(lengths)
    return {
        "files": [str(p) for p in paths],
        "rows": rows,
        "rows_with_problems": bad,
        "problems": dict(problems),
        "conversations": len(conversations),
        "tokens": total,
        "loss_tokens": sum(completions),
        "row_tokens": percentiles(lengths),
        "completion_tokens": percentiles(completions),
        "finish_reasons": dict(finish),
        "rows_over_max_seq_length": sum(n > max_seq_length for n in lengths),
        "tokens_cut_at_max_seq_length": sum(max(0, n - max_seq_length) for n in lengths),
        "max_seq_length": max_seq_length,
    }


def split(
    paths: list[Path], heldout_ids: set[str], out_dir: Path, by: str = "row"
) -> dict[str, int]:
    out_dir.mkdir(parents=True, exist_ok=True)
    counts = Counter()
    with (
        (out_dir / "train.jsonl").open("w") as train,
        (out_dir / "heldout.jsonl").open("w") as held,
    ):
        for path in paths:
            with path.open() as handle:
                for line in handle:
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    key = str(row.get("id")) if by == "row" else conversation_id(row)
                    side = "heldout" if key in heldout_ids else "train"
                    (held if side == "heldout" else train).write(
                        line if line.endswith("\n") else line + "\n"
                    )
                    counts[side] += 1
    return dict(counts)


def prompts(path: Path, out: Path, limit: int, max_prompt_tokens: int) -> dict[str, int]:
    """Write ``{"id", "prompt_ids"}`` for the first ``limit`` rows whose prompt fits."""
    counts: Counter[str] = Counter()
    with path.open() as handle, out.open("w") as sink:
        for line in handle:
            if counts["written"] >= limit:
                break
            if not line.strip():
                continue
            row = json.loads(line)
            first = next((i for i, m in enumerate(row["loss_mask"]) if m), None)
            if first is None or first > max_prompt_tokens:
                counts["skipped"] += 1
                continue
            sink.write(json.dumps({"id": row["id"], "prompt_ids": row["input_ids"][:first]}) + "\n")
            counts["written"] += 1
    return dict(counts)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="apertus-eagle-speculators-corpus")
    sub = parser.add_subparsers(dest="command", required=True)
    c = sub.add_parser("check")
    c.add_argument("--input", type=Path, nargs="+", required=True)
    c.add_argument("--max-seq-length", type=int, default=8192)
    c.add_argument("--report", type=Path, required=True)
    s = sub.add_parser("split")
    s.add_argument("--input", type=Path, nargs="+", required=True)
    s.add_argument("--heldout-ids", type=Path, required=True, help="one id per line")
    s.add_argument("--by", choices=("row", "conversation"), default="row")
    s.add_argument("--output-dir", type=Path, required=True)
    q = sub.add_parser("prompts")
    q.add_argument("--input", type=Path, required=True)
    q.add_argument("--output", type=Path, required=True)
    q.add_argument("--limit", type=int, default=128)
    q.add_argument("--max-prompt-tokens", type=int, default=2048)
    args = parser.parse_args(argv)
    if args.command == "prompts":
        print(json.dumps(prompts(args.input, args.output, args.limit, args.max_prompt_tokens)))
    elif args.command == "check":
        report = check(args.input, args.max_seq_length)
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2) + "\n")
        print(json.dumps({k: v for k, v in report.items() if k != "files"}))
    else:
        ids = {line.strip() for line in args.heldout_ids.read_text().splitlines() if line.strip()}
        counts = split(args.input, ids, args.output_dir, args.by)
        # Every listed id must be found, or the held-out set is not the one intended.
        counts["heldout_ids_listed"] = len(ids)
        print(json.dumps(counts))
        if args.by == "row" and counts.get("heldout", 0) != len(ids):
            raise SystemExit(f"matched {counts.get('heldout', 0)} of {len(ids)} held-out ids")


if __name__ == "__main__":
    main()
