image = "ghcr.io/swiss-ai/vllm_apertus_1.5_release:latest-arm64"
mounts = ["/capstor", "/iopsstor", "/users"]
workdir = "/capstor/scratch/cscs/zyu/spec"
entrypoint = false

[env]
HF_HOME = "/capstor/scratch/cscs/zyu/spec/hf"
HF_HUB_OFFLINE = "1"
SPEC = "/capstor/scratch/cscs/zyu/spec"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda13"
